# Generated by Django 3.2.9 on 2022-03-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
