# Generated by Django 3.2.9 on 2022-03-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0002_petprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='pet_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
