# Generated by Django 3.2.9 on 2022-01-24 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0002_rename_image_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
