# Generated by Django 3.2.9 on 2022-03-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0002_auto_20220320_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
