# Generated by Django 3.2.9 on 2022-03-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0003_alter_breed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='adult',
            field=models.BooleanField(default=False),
        ),
    ]
