# Generated by Django 3.2.9 on 2022-03-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogapp', '0003_petprofile_pet_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='pet_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
