# Generated by Django 3.2.9 on 2022-03-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0004_auto_20220318_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TrainingCategory',
        ),
    ]
