# Generated by Django 3.2.9 on 2022-03-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_loggedinuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
